sonar.projectKey=skillsync-auth-service
sonar.projectName=SkillSync - Auth Service
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=http://localhost:9000
sonar.token=YOUR_TOKEN_HERE
sonar.language=java
sonar.sourceEncoding=UTF-8