server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/HP/OneDrive/Desktop/SkillSync/Backend/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
