server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/notifications_db?createDatabaseIfNotExist=true
    username: root
    password: tanisha
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: bd75d4b1fb1194
    password: 0af8cb94fe484c
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          ssl:
            trust: sandbox.smtp.mailtrap.io
          starttls:
            enable: true

app:
  mail:
    from: no-reply@skillsync.test

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.skillsync.notificationservice

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: mysecretkeymysecretleymysecretkey32
  expiration: 86400000

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

logging:
  level:
    com.skillsync: DEBUG
